/**
 * Location keywords and service areas for SEO. Main keyword list lives in ../keywords.ts
 */
export const LOCATION_KEYWORDS = [
  "new homes near Miami",
  "rent to own Miami",
  "homes for sale near Miami",
  "new construction near Miami",
  "home builder near Miami",
  "Miami area homes",
  "South Miami homes",
  "new homes Fort Myers",
  "rent to own Fort Myers",
  "homes for sale Fort Myers",
  "new construction Fort Myers",
  "home builder Fort Myers",
  "Fort Myers area homes",
  "near Fort Myers homes",
  "new homes Cape Coral",
  "rent to own Cape Coral",
  "homes for sale Cape Coral",
  "new construction Cape Coral",
  "home builder Cape Coral",
  "new homes near Naples",
  "rent to own near Naples",
  "homes for sale near Naples",
  "new construction near Naples",
  "home builder near Naples",
  "new homes Lehigh Acres",
  "rent to own Lehigh Acres",
  "homes for sale Lehigh Acres",
  "new construction Lehigh Acres",
  "home builder Lehigh Acres",
  "new homes LaBelle",
  "rent to own LaBelle",
  "homes for sale LaBelle",
  "new construction LaBelle",
  "home builder LaBelle",
  "new homes Clewiston",
  "new homes Alva",
  "new homes Immokalee",
  "homes within 2 hours of Miami",
  "homes within 2 hours of Fort Myers",
  "Southwest Florida home builder",
  "Hendry County homes",
  "Glades County homes",
  "Lee County homes",
] as const;

export const SERVICE_AREAS = [
  { name: "LaBelle", state: "FL", distance: "0 miles" },
  { name: "Lehigh Acres", state: "FL", distance: "15 miles" },
  { name: "Fort Myers", state: "FL", distance: "30 miles" },
  { name: "Cape Coral", state: "FL", distance: "35 miles" },
  { name: "Naples", state: "FL", distance: "45 miles" },
  { name: "Clewiston", state: "FL", distance: "20 miles" },
  { name: "Immokalee", state: "FL", distance: "25 miles" },
  { name: "Alva", state: "FL", distance: "10 miles" },
  { name: "Miami", state: "FL", distance: "100 miles" },
  { name: "Punta Gorda", state: "FL", distance: "50 miles" },
] as const;
